/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  Overrides,
  BigNumberish,
  BytesLike,
  BigNumber,
} from "fuels";

export type AddressStruct = { value: string };

export type ContractIdStruct = { value: string };

interface EscrowAbiInterface extends Interface {
  functions: {
    "constructor(struct Address,struct Address,struct ContractId,u64)": FunctionFragment;
    "deposit()": FunctionFragment;
    "approve()": FunctionFragment;
    "withdraw()": FunctionFragment;
    "get_balance()": FunctionFragment;
    "get_user_data(struct Address)": FunctionFragment;
    "get_state()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "constructor",
    values: [AddressStruct, AddressStruct, ContractIdStruct, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(functionFragment: "approve", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "get_balance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "get_user_data",
    values: [AddressStruct]
  ): string;
  encodeFunctionData(functionFragment: "get_state", values?: undefined): string;

  decodeFunctionData(
    functionFragment: "constructor",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "deposit",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "approve",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "withdraw",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_balance",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_user_data",
    data: BytesLike
  ): DecodedValue;
  decodeFunctionData(
    functionFragment: "get_state",
    data: BytesLike
  ): DecodedValue;
}

export class EscrowAbi extends Contract {
  interface: EscrowAbiInterface;
  functions: {
    constructor(
      buyer: AddressStruct,
      seller: AddressStruct,
      asset: ContractIdStruct,
      asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    "constructor(struct Address,struct Address,struct ContractId,u64)"(
      buyer: AddressStruct,
      seller: AddressStruct,
      asset: ContractIdStruct,
      asset_amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    deposit(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    "deposit()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    approve(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    "approve()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    withdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    "withdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<boolean>;

    get_balance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "get_balance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    get_user_data(
      user: AddressStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    "get_user_data(struct Address)"(
      user: AddressStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    get_state(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "get_state()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  constructor(
    buyer: AddressStruct,
    seller: AddressStruct,
    asset: ContractIdStruct,
    asset_amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  "constructor(struct Address,struct Address,struct ContractId,u64)"(
    buyer: AddressStruct,
    seller: AddressStruct,
    asset: ContractIdStruct,
    asset_amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  deposit(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  "deposit()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  approve(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  "approve()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  withdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  "withdraw()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<boolean>;

  get_balance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;

  "get_balance()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;

  get_user_data(
    user: AddressStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  "get_user_data(struct Address)"(
    user: AddressStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  get_state(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;

  "get_state()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BigNumber>;
}
