/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type {
  Interface,
  FunctionFragment,
  DecodedValue,
  Contract,
  Overrides,
  BigNumberish,
  BytesLike,
} from 'fuels';

export type AddressInput = { value: string };

export type Address = { value: string };

export type ContractIdInput = { value: string };

export type ContractId = { value: string };

export type IdentityInput = {
  Address: AddressInput;
  ContractId: ContractIdInput;
};

export type Identity = { Address: Address; ContractId: ContractId };

export type AssetInput = { amount: BigNumberish; id: ContractIdInput };

export type Asset = { amount: bigint; id: ContractId };

export type UserInput = {
  approved: boolean;
  asset: ContractIdInput;
  exists: boolean;
  deposited: boolean;
};

export type User = {
  approved: boolean;
  asset: ContractId;
  exists: boolean;
  deposited: boolean;
};

interface EscrowAbiInterface extends Interface {
  submit: {
    constructor: FunctionFragment;
    deposit: FunctionFragment;
    approve: FunctionFragment;
    withdraw: FunctionFragment;
    get_balance: FunctionFragment;
    get_user_data: FunctionFragment;
    get_state: FunctionFragment;
  };
  submitResult: {
    constructor: FunctionFragment;
    deposit: FunctionFragment;
    approve: FunctionFragment;
    withdraw: FunctionFragment;
    get_balance: FunctionFragment;
    get_user_data: FunctionFragment;
    get_state: FunctionFragment;
  };
  dryRun: {
    constructor: FunctionFragment;
    deposit: FunctionFragment;
    approve: FunctionFragment;
    withdraw: FunctionFragment;
    get_balance: FunctionFragment;
    get_user_data: FunctionFragment;
    get_state: FunctionFragment;
  };
  dryRunResult: {
    constructor: FunctionFragment;
    deposit: FunctionFragment;
    approve: FunctionFragment;
    withdraw: FunctionFragment;
    get_balance: FunctionFragment;
    get_user_data: FunctionFragment;
    get_state: FunctionFragment;
  };
  prepareCall: {
    constructor: FunctionFragment;
    deposit: FunctionFragment;
    approve: FunctionFragment;
    withdraw: FunctionFragment;
    get_balance: FunctionFragment;
    get_user_data: FunctionFragment;
    get_state: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'constructor', values: [any, any]): Uint8Array;
  encodeFunctionData(functionFragment: 'deposit', values?: undefined): Uint8Array;
  encodeFunctionData(functionFragment: 'approve', values?: undefined): Uint8Array;
  encodeFunctionData(functionFragment: 'withdraw', values?: undefined): Uint8Array;
  encodeFunctionData(functionFragment: 'get_balance', values: [ContractIdInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_user_data', values: [IdentityInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'get_state', values?: undefined): Uint8Array;

  decodeFunctionData(functionFragment: 'constructor', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'deposit', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'approve', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'withdraw', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_balance', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_user_data', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'get_state', data: BytesLike): DecodedValue;
}

export class EscrowAbi extends Contract {
  interface: EscrowAbiInterface;
  submit: {
    constructor(
      users: any,
      assets: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    approve(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    get_balance(
      asset: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    get_user_data(
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<User>;

    get_state(overrides?: Overrides & { from?: string | Promise<string> }): Promise<bigint>;
  };
  submitResult: {
    constructor(
      users: any,
      assets: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    approve(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    get_balance(
      asset: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    get_user_data(
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<User>;

    get_state(overrides?: Overrides & { from?: string | Promise<string> }): Promise<bigint>;
  };
  dryRun: {
    constructor(
      users: any,
      assets: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    approve(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    get_balance(
      asset: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    get_user_data(
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<User>;

    get_state(overrides?: Overrides & { from?: string | Promise<string> }): Promise<bigint>;
  };
  dryRunResult: {
    constructor(
      users: any,
      assets: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    approve(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    get_balance(
      asset: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    get_user_data(
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<User>;

    get_state(overrides?: Overrides & { from?: string | Promise<string> }): Promise<bigint>;
  };
  prepareCall: {
    constructor(
      users: any,
      assets: any,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<void>;

    deposit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    approve(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

    get_balance(
      asset: ContractIdInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<any>;

    get_user_data(
      user: IdentityInput,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<User>;

    get_state(overrides?: Overrides & { from?: string | Promise<string> }): Promise<bigint>;
  };

  constructor(
    users: any,
    assets: any,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<void>;

  deposit(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

  approve(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

  withdraw(overrides?: Overrides & { from?: string | Promise<string> }): Promise<void>;

  get_balance(
    asset: ContractIdInput,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<any>;

  get_user_data(
    user: IdentityInput,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<User>;

  get_state(overrides?: Overrides & { from?: string | Promise<string> }): Promise<bigint>;
}
