/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from 'fuels';
import { Interface, Contract } from 'fuels';
import type { EscrowAbi, EscrowAbiInterface } from '../EscrowAbi';
const _abi = [
  {
    type: 'function',
    inputs: [
      {
        name: 'users',
        type: '[enum Identity; 2]',
        components: [
          {
            name: '__array_element',
            type: 'enum Identity',
            components: [
              {
                name: 'Address',
                type: 'struct Address',
                components: [
                  {
                    name: 'value',
                    type: 'b256',
                    components: null,
                  },
                ],
              },
              {
                name: 'ContractId',
                type: 'struct ContractId',
                components: [
                  {
                    name: 'value',
                    type: 'b256',
                    components: null,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'assets',
        type: '[struct Asset; 2]',
        components: [
          {
            name: '__array_element',
            type: 'struct Asset',
            components: [
              {
                name: 'amount',
                type: 'u64',
                components: null,
              },
              {
                name: 'id',
                type: 'struct ContractId',
                components: [
                  {
                    name: 'value',
                    type: 'b256',
                    components: null,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    name: 'constructor',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [],
    name: 'deposit',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [],
    name: 'approve',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [],
    name: 'withdraw',
    outputs: [
      {
        name: '',
        type: '()',
        components: [],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'asset',
        type: 'struct ContractId',
        components: [
          {
            name: 'value',
            type: 'b256',
            components: null,
          },
        ],
      },
    ],
    name: 'get_balance',
    outputs: [
      {
        name: '',
        type: '(bool, u64)',
        components: [
          {
            name: '__tuple_element',
            type: 'bool',
            components: null,
          },
          {
            name: '__tuple_element',
            type: 'u64',
            components: null,
          },
        ],
      },
    ],
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'user',
        type: 'enum Identity',
        components: [
          {
            name: 'Address',
            type: 'struct Address',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
          {
            name: 'ContractId',
            type: 'struct ContractId',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
        ],
      },
    ],
    name: 'get_user_data',
    outputs: [
      {
        name: '',
        type: 'struct User',
        components: [
          {
            name: 'approved',
            type: 'bool',
            components: null,
          },
          {
            name: 'asset',
            type: 'struct ContractId',
            components: [
              {
                name: 'value',
                type: 'b256',
                components: null,
              },
            ],
          },
          {
            name: 'exists',
            type: 'bool',
            components: null,
          },
          {
            name: 'deposited',
            type: 'bool',
            components: null,
          },
        ],
      },
    ],
  },
  {
    type: 'function',
    inputs: [],
    name: 'get_state',
    outputs: [
      {
        name: '',
        type: 'u64',
        components: null,
      },
    ],
  },
];

export class EscrowAbi__factory {
  static readonly abi = _abi;
  static createInterface(): EscrowAbiInterface {
    return new Interface(_abi) as EscrowAbiInterface;
  }
  static connect(id: string, walletOrProvider: Wallet | Provider): EscrowAbi {
    return new Contract(id, _abi, walletOrProvider) as EscrowAbi;
  }
}
